name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: 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
          USERNAME: Rero0124
      - name: Commit & Push
        run: |
          git config user.name Rero0124
          git config user.email kimseung0930@gmail.com
          git add -A .
          git commit -m "generated"
          git push
